title: "Lab 5_SamSilva"
author: "Sam Silva
date: "2/19/2020"
output: html_document
---

```{r}
library (tidyverse)
```

```{r}
SNPs <- read_tsv("23andMe_complete.txt", skip = 14, col_types = 
  cols(chromosome = col_factor()))
```

```{r}
####Exercise 1
SNPs%>%
  select(position,genotype)
```


```{r}
####Exercise 2
 SNPs%>%
   select(chromosome,genotype)%>%
  filter(chromosome == "MT")%>%
  filter(genotype != "A")%>%
  filter (genotype != "T")
```


```{r}
####Exercise 3
SNPs%>%
    group_by(chromosome)%>%
    summarize(min_position = min(position), max_position = max(position), n=n())
```


```{r}
####Exercise 4
SNPs%>%
   group_by(chromosome) %>%
   summarize(min_position = min(position),
   max_position = max(position),n= n())%>%
  mutate(SNPs_density = sum(max_position, -min_position) / n)
```

```{r}
####Exercise 5
SNPs%>%
   group_by(chromosome) %>%
   summarize( min_position = min(position),
   max_position = max(position), n= n())%>%
   mutate(SNPs_density = sum(max_position, -min_position) / n)%>%
  arrange(desc(SNPs_density))
```

```{r}
SNPs_complete<- SNPs%>%
   group_by(chromosome) %>%
   summarize( min_position = min(position),
   max_position = max(position), n= n())%>%
   mutate(SNPs_density = sum(max_position, -min_position) / n)%>%
  arrange(desc(SNPs_density))

```

```{r}
####Exercise 6
write_csv(SNPs_complete, path = "SNPs_complete.csv")
```
